// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZr7aS7HiAseDOrAjVifqKbKrbe0heFU',
    appId: '1:1084015809711:android:6803b2748c55795eb5305a',
    messagingSenderId: '1084015809711',
    projectId: 'bharatsocials-52908',
    storageBucket: 'bharatsocials-52908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFCq1mPWnMYtBChNN4RD0jF3ZfxLoXzw',
    appId: '1:1084015809711:ios:6563323c1195db32b5305a',
    messagingSenderId: '1084015809711',
    projectId: 'bharatsocials-52908',
    storageBucket: 'bharatsocials-52908.appspot.com',
    androidClientId: '1084015809711-odnvdgtcprpjmg2oo9dcbjfb9r2e7aeo.apps.googleusercontent.com',
    iosClientId: '1084015809711-u4vjg1e3v0adkkj53hkf7a60c3acoiqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bharatsocials',
  );

}